services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - --api.dashboard=true
      - --api.insecure=false
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --certificatesresolvers.le.acme.httpchallenge=true
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.le.acme.email=admin@seely.com.ar
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt
    networks:
      - app-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.seely.com.ar`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=le"

  auth-api-be:
    build: ./auth-api-be
    container_name: auth-api-be
    env_file:
      - ./auth-api-be/.env
    depends_on:
      - rabbitmq
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth-api.rule=Host(`auth.seely.com.ar`)"
      - "traefik.http.routers.auth-api.entrypoints=websecure"
      - "traefik.http.routers.auth-api.tls.certresolver=le"
      - "traefik.http.services.auth-api.loadbalancer.server.port=8082"
    networks:
      - app-net
    ports:
      - "8082:8082"

  assistant-ia-api:
    build: ./assistant-ia-api
    container_name: assistant-ia-api
    env_file:
      - ./assistant-ia-api/.env
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./assistant-ia-api:/app
      - ./global-bundle.pem:/app/global-bundle.pem
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.assistant-api.rule=Host(`assistant.seely.com.ar`)"
      - "traefik.http.routers.assistant-api.entrypoints=websecure"
      - "traefik.http.routers.assistant-api.tls.certresolver=le"
      - "traefik.http.services.assistant-api.loadbalancer.server.port=8000"
    networks:
      - app-net
    ports:
      - "8000:8000"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rabbitmq.rule=Host(`mq.seely.com.ar`)"
      - "traefik.http.routers.rabbitmq.entrypoints=websecure"
      - "traefik.http.routers.rabbitmq.tls.certresolver=le"
      - "traefik.http.services.rabbitmq.loadbalancer.server.port=15672"
    networks:
      - app-net

volumes:
  db_data:
    driver: local

networks:
  app-net:
    driver: bridge
